version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
     - location: stop_server.sh
       timeout: 300
       runas: root
  AfterInstall:
    - location: start_server.sh
      timeout: 300
      runas: root
